### ISSUE TITLE
NativeAppAuthClient has not attribute '_app'

### ISSUE THREAD

**Issue by JBorrow** [globus/globus-sdk-python#1009]
We are seeing problems in our production code that are only present with the latest release, and tie back to PR #993.

Specifically, we are getting this traceback:

```
librarian-postgres  | (renewing:ensure_valid_token) [2024-07-19 16:01:02,213] {DEBUG}:RenewingAuthorizer checking expiration time
librarian-postgres  | (renewing:ensure_valid_token) [2024-07-19 16:01:02,213] {DEBUG}:RenewingAuthorizer has a token, but it is expired
librarian-postgres  | (renewing:ensure_valid_token) [2024-07-19 16:01:02,213] {DEBUG}:RenewingAuthorizer fetching new Access Token
librarian-postgres  | (native_client:oauth2_refresh_token) [2024-07-19 16:01:02,213] {INFO}:Executing token refresh without client credentials
librarian-postgres  | (base_login_client:oauth2_token) [2024-07-19 16:01:02,214] {INFO}:Fetching new token from Globus Auth
librarian-postgres  | (client:post) [2024-07-19 16:01:02,214] {DEBUG}:POST to /v2/oauth2/token with query_params None
librarian-postgres  | (core:_run_job) [2024-07-19 16:01:02,218] {ERROR}:Traceback (most recent call last):
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/librarian_background/core.py", line 38, in _run_job
librarian-postgres  |     super()._run_job(job)
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/schedule/__init__.py", line 173, in _run_job
librarian-postgres  |     ret = job.run()
librarian-postgres  |           ^^^^^^^^^
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/schedule/__init__.py", line 691, in run
librarian-postgres  |     ret = self.job_func()
librarian-postgres  |           ^^^^^^^^^^^^^^^
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/librarian_background/task.py", line 41, in __call__
librarian-postgres  |     return self.on_call()
librarian-postgres  |            ^^^^^^^^^^^^^^
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/librarian_background/queues.py", line 85, in on_call
librarian-postgres  |     self.core(session_maker=get_session)
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/librarian_background/queues.py", line 76, in core
librarian-postgres  |     check_on_consumed(
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/librarian_background/queues.py", line 137, in check_on_consumed
librarian-postgres  |     current_status = queue_item.async_transfer_manager.transfer_status(
librarian-postgres  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/hera_librarian/async_transfers/globus.py", line 246, in transfer_status
librarian-postgres  |     task_doc = transfer_client.get_task(self.task_id)
librarian-postgres  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/globus_sdk/services/transfer/client.py", line 1654, in get_task
librarian-postgres  |     return self.get(f"task/{task_id}", query_params=query_params)
librarian-postgres  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/globus_sdk/client.py", line 255, in get
librarian-postgres  |     return self.request(
librarian-postgres  |            ^^^^^^^^^^^^^
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/globus_sdk/client.py", line 425, in request
librarian-postgres  |     r = self.transport.request(
librarian-postgres  |         ^^^^^^^^^^^^^^^^^^^^^^^
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/globus_sdk/transport/requests.py", line 315, in request
librarian-postgres  |     self._set_authz_header(authorizer, req)
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/globus_sdk/transport/requests.py", line 251, in _set_authz_header
librarian-postgres  |     authz_header = authorizer.get_authorization_header()
librarian-postgres  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/globus_sdk/authorizers/renewing.py", line 168, in get_authorization_header
librarian-postgres  |     self.ensure_valid_token()
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/globus_sdk/authorizers/renewing.py", line 162, in ensure_valid_token
librarian-postgres  |     self._get_new_access_token()
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/globus_sdk/authorizers/renewing.py", line 122, in _get_new_access_token
librarian-postgres  |     res = self._get_token_response()
librarian-postgres  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/globus_sdk/authorizers/refresh_token.py", line 85, in _get_token_response
librarian-postgres  |     return self.auth_client.oauth2_refresh_token(self.refresh_token)
librarian-postgres  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/globus_sdk/services/auth/client/native_client.py", line 134, in oauth2_refresh_token
librarian-postgres  |     return self.oauth2_token(form_data, body_params=body_params)
librarian-postgres  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/globus_sdk/services/auth/client/base_login_client.py", line 403, in oauth2_token
librarian-postgres  |     self.post(
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/globus_sdk/client.py", line 279, in post
librarian-postgres  |     return self.request(
librarian-postgres  |            ^^^^^^^^^^^^^
librarian-postgres  |   File "/usr/local/lib/python3.11/site-packages/globus_sdk/client.py", line 418, in request
librarian-postgres  |     if self._app and self.resource_server:
librarian-postgres  |        ^^^^^^^^^
librarian-postgres  | AttributeError: 'NativeAppAuthClient' object has no attribute '_app'
librarian-postgres  |
```

With python3.11 and version 3.42.0.

Our code is open source, and is relatively isolated: https://github.com/simonsobs/librarian/blob/main/hera_librarian/async_transfers/globus.py

**Comment by derek-globus** [comment]
Hey Josh, thanks for reporting!

We released an experimental new auth management construct in 3.42.0 which included a change to our BaseClient class. Our internal testing showed this to be non-impactful for existing Client usages like the one you describe here but seems we may have missed something.

We're investigating this now & will update here once it's identified and/or resolved.
In the meantime if this is a critical function, I'd recommend pinning v3.41.0 temporarily.

**Comment by sirosen** [comment]
Hi there! A few of our team members talked about this issue and we think we know what's happening.

We weren't able to find any trivial reproducer, so we started to look more closely at the `librarian` system you linked to, in order to see anything which might provide a clue.
It looks like your codebase is maintaining several columns which contain pickled objects. So we think you have a `NativeAppAuthClient` object from before v3.42.0, pickled it, and then unpickled it on the new version.

I don't want to digress too far into recommendations around safe and proper use of `pickle` as a data format -- it may be appropriate to your use-case -- but for an object provided by a library to be compatible across versions, for pickle dumping and loading, it must meet a very high standard.[^1] We don't maintain version-to-version pickle compatibility promises across any of our objects. We maintain interface compatibility.

[^1]: This standard is only met by either _never_ adding attributes or only adding them with very special care. It is incidentally met, which is why you often won't see issues, if a class does not change very often.

Pickling and unpickling client objects isn't a supported mode of usage for the `globus_sdk` -- at least, not across version boundaries. Unpickling skips `__init__`. It invokes the constructor (`__new__`), and then attaches attributes to the new object directly. This means that any necessary code in `__init__` like [this line](https://github.com/globus/globus-sdk-python/blob/7ecb1af26c3af29f73d433f59df58e21c7514778/src/globus_sdk/client.py#L125) which initializes `self._app` (with a default of `None`) never runs.[^2]

[^2]: This is merely upgrade compatibility! I can construe scenarios in which changes to initializers could have significant negative implications for _downgrade_ compatibility, which IMO is even scarier as a system operator. But I digress...

If we're correct (I'm not aware of any other equally good explanation), then there are a few things you can do to start to resolve this. They all involve code changes on your end. Two solutions are:

## Cheat! Add attributes!

I can't condone this but, partly in the interest of explaining the problem, I want to note that it would _probably_ work and it would be _probably_ fine. If we take a look at the diff between 3.41.0 and 3.42.0 for `src/globus_sdk/client.py`, we find two attributes have been added to `__init__`, both with defaults of `None`: `_app` and `app_scopes`.
These can be patched into place:
```python
client = pickle.loads(some_binary_data)
assert isinstance(client, globus_sdk.BaseClient)
client._app = None
client.app_scopes = None
```

This is inelegant and hacky, but that is fundamentally "the issue". Something pickled on an old version doesn't match the attributes of a newer version.

I would only consider this if you _must_ upgrade and you _can't_ invest more heavily in making your code more gracefully compatible. You might be able to get this kind of fix into place by overriding some of the pickle protocol hooks, like `globus_sdk.BaseClient.__reduce__`. It's still not supported usage, but this could help you get past this particular issue.

## Migrate off of pickled objects, then upgrade

This is the best solution. It fixes the fundemtal issue: pickling objects which do not have a clear and documented support paradigm _specifically for `pickle`_ reduces your system's compatibility with various library versions.

You need to get away from pickling objects which you don't control, and which don't make promises that a pickled object from version X will be safely and correctly unpickled on version Y. If your codebase defines a class, it clearly can maintain whatever compatibility promises are necessary for pickle/unpickle.

What a migration effort, limited to globus-sdk objects, will look like will depend largely on the breadth of your usage. From what I see, you have some code related to building authorizers and Auth clients, and then use those to build a TransferClient, which is your primary object of interest.
You'll need to make sure that all of the relevant data are stored in some non-pickle format (e.g., JSON) and then loaded and passed back into fresh objects. Off the top of my head, based on what I see in `librarian`, you'll need:
- any tokens (access tokens ideally, but minimally refresh tokens)
- client IDs
- client secrets (for confidential apps)

That will be enough information to reinstantiate objects when loaded.
You'll need to define your new storage format, develop a transitional load/dump paradigm which can migrate data from the existing pickled format, and then, later, drop support for pickled data.

This is a nontrivial data migration, but it's the best path to ensure that you aren't building a tightly coupled system in which you can't continue to upgrade your library versions.

### Discard existing creds if possible

If you can _discard_ the existing data, your migration work will be much easier. I don't have much context around your usage, so I don't know if that would be permissible. But this saves you writing any kind of migratory compatibility code -- you just drop the old storage and add new storage.

## Until you are ready, pin to the last known-working version

globus-sdk v3.41.0 _should_ work for you, but we can't really guarantee even that, if objects are passing across versions through the pickle protocol.
The only promise I think we can make, vis-a-vis pickle, is that whatever version last worked will continue working.

I would be concerned trying to move pickled objects across any version boundary, but it's especially worth noting that we have started to emit warnings about usages which will change in v4.0.0. Almost certainly, once we release v4.0, you'll have to solve these same problems. (We don't have a timeline yet, but we're starting to plan out work for a distant future 4.0 release.)

## Let us know how we can help

We're happy to engage with you and help support you as you work on this. You can contact us here or via support@globus.org.

We can definitely offer suggestions for workarounds, like the above, and we can help you work with any of our supported patterns of usage, like the `on_refresh` callback for `RefreshTokenAuthorizer`, which may turn out to be relevant to your work.

**Comment by JBorrow** [comment]
Hi, thanks for this! Yes, I believe what you are saying is true. We are accidentally writing back these objects to our database instead of re-creating it on load from the required information. I will give that a go in the next week or so and get back to you as to whether it fixed our issue or not.

**Comment by sirosen** [comment]
That sounds great! Sorry if the above was information overload. We're always available to help out.
We're talking about making client objects warn or error when pickled, which might help. I'll leave this issue open until we have a decision (and/or implementation) around that.

**Comment by sirosen** [comment]
I decided to stop looking into emitting warnings on pickling and unpickling after a bit of investigation and play last week.

We don't currently have pickle protocol hooks like `__reduce__`, `__getstate__`, or `__setstate__` defined for client objects, meaning we inherit the defaults from `object`. It's not possible to hook in and start warning without defining an interface around this. At that point, it starts to be more confusing, rather than less so, what we support, since we'd have to very explicitly consider `pickle` compatibility to write those hooks -- and we'd need to start testing them.

We can address this in v4.0 by making it an error to pickle a client, but I'm not certain that we should do even that. I can imagine usages (although I'm not aware of any, in practice) which are safe and which we'd be breaking unnecessarily with such a change.

With simonsobs/librarian#78 now open, I'm going to mark this as resolved.
