### ISSUE TITLE
invalid_client errors not being json parsed

### ISSUE THREAD

**Issue by aaschaer** [globus/globus-sdk-python#138]
The following error: {"error": "invalid_client"} is defaulting to text and logging a complaint about malformed json.

Not a huge issue, since defaulting to text doesn’t loose any information in this case, but we might want to edit GlobusAPIError._load_from_json() to handle these in the future.

**Comment by bjmc** [comment]
Arguably this is a Auth bug, rather than an SDK bug. That error is raised by the oauthlib library, instead of our application code. We have [an open issue](https://github.com/globusonline/globus-auth/issues/825) to catch all the OAuthlib errors and re-raise them as standard Globus Auth errors with our full set of normal JSON error fields.

**Comment by sirosen** [comment]
While I'm usually happy to shirk any blame if you'll let me, I think there's some culpability here too.
Auth may want to improve its error formats, but it's fair to call it a bug that the SDK isn't specializing its error handling for Auth the way it does for Transfer.

Having a text field named `"error"` seems pretty sane. We shouldn't be completely helpless in the face of such an unusual and novel error format. :wink:
