### ISSUE TITLE
Improving response classes

### ISSUE THREAD

**Issue by bd4** [globus/globus-sdk-python#23]
I find myself constantly forgetting to add the `.data`, and it seems superfluous. I think it's especially confusing for the iter responses. I propose that we add a `__getitem__` to `GlobusResponse` that operates on the `.data`, so you can do `response['path']` instead of `response.data['path']`, and make it have a default `__next__` that directly exposes `response['DATA']`. That makes it more convenient, while still giving us a central response class that we can tweak in the future if needed.

With the current response formats, it feels like Java, not like Python.

**Comment by bd4** [comment]
I'd also like to kill `.json_body`, it's confusing having two ways to access the same thing. Maybe we should rename `.text_body` to just text, it was designed to be symmetric with the params to `.get(...)` and friends, but I don't think that actually buys anything.

**Comment by bd4** [comment]
The `DATA` iter thing is very specific to the Transfer client, so that should be in a subclass, but `__getitem__` may be general enough to live in the base. If the response is not JSON, it could raise `TypeError` or similar.

**Comment by sirosen** [comment]
I approve of this message in principle, but I think we need to be careful to not tread on the toes of a non-Transfer API that gives non-JSON responses.
Transfer is very good about JSON everywhere, all the time, but it's not just a matter of being well behaved: other APIs may have use cases that warrant a different format.

So, my thoughts on how to do this:

- Keep the `data` property -- I like having something I can turn to and say "If a response type wants to define what all of its contents look like as a python object, do so here and only here."
- `GlobusResponse` gets a `__getitem__` method which tries to do a `__getitem__` on whatever its `data` property is. That way, non-`TransferResponse` and non-`GlobusHTTPResponse` classes can make themselves a `__getitem__` by simply ensuring that it works on `.data`. Likely that will typically a dict. Otherwise, we get a lot of same-y `__getitem__` definitions in a bunch of classes, and it gets ugly.
- If `TransferResponse` has iterable responses, that's fine, but I think it's very ugly to throw a `KeyError` if something doesn't have the `DATA` field. Either use a specialized subclass, or make iterability an option to the `TransferResponse` constructor. Attempting to iterate non-iterable responses should be a `TypeError` (just put that in `__next__`, I think?)
- Paging calls will not suddenly start returning a `TransferResponse` object -- I don't see a way of having a generic `TransferResponse` be responsible for paging without contorting things significantly. We might make `PaginatedResource` a `TransferResponse` subclass and maybe rename it.

More questions:
- Should we wrap `TypeError` on failing `__getitem__` or `__next__` in a `GlobusError` of some kind? `GlobusUsageError`?
- Do we want to do multiple-inheritance for `TransferResponse` to be a `GlobusHTTPResponse` and a `six.Iterator`, or should we just define `next` as an alias for `__next__` ourselves? It seems like a typical use case for multiple inheritance, but I don't want to have messy MRO questions down the road.


I also agree with the idea that it's time to get rid of `.json_body`.
I can't quite remember the rationale at the time for supplanting it with `.data`, other than it being shorter, but `json_body` feels fairly specific to HTTP responses.

I'm going to take a crack at this tonight in a branch, and we can discuss more tomorrow.

**Comment by sirosen** [comment]
You can see my progress thusfar in `refactor/improved-responses`

Worth noting: things get tricky if you try to do multiple classes of response for `TransferClient`.
It turned out to be much easier to give `TransferResponse` an `__iter__` and to have it raise a `TypeError` explicitly if iteration isn't turned on.
Turns out that renders the above question about `TransferResponse` being an iterator moot -- it's an iterable now, not an iterator.
