### ISSUE TITLE
trusted endpoint organization

### ISSUE THREAD

**Issue by vsoch** [globus/globus-sdk-python#270]
I'm not sure if this is the right board to post on, but here goes! I'm interested in what would be a good way to go about making an endpoint "trusted" in terms of it's organization. This means that, if I have endpoint A and call it a "sregistry endpoint" I can be guaranteed to file a particular kind of organization and type of file. I can give it some configuration to determine the structure, and if I (or anyone else) try to do an operation that goes against the expected structure I am not allowed. I can then associate this predictability with a label for others to find. Even better, I can also set constraints like this for metadata, so I can be sure that these endpoints provide something that looks like an API for associated metadata (and I think worst case some json file named equivalently to the image could be stored alongside each image for reading it, albeit it's not queryable). The use case looks like this:

1. I create a local registry (an organized storage folder) of Singularity images. This means that an organization is expected of collection folders with images named based on URIs, and that no files other than Singularity will be found in there.
2. I register my endpoint for some discovery tool so other uses can easily find it. I don't give anyone write permission, but I give global read permission so anyone can grab my images.
3. Then when I am interested in getting images from others, I use the discovery endpoint to search and filter down to some image I'm interested in. I do a "pull" sort of operation and get the image into my space locally, **or** just save the endpoint where I found it and other metadata for later usage.

**Comment by sirosen** [comment]
This sounds like a really interesting use-case, but I don't see any simple way to leverage existing Globus tools or services to do it.
If I narrow my thinking to just what's relevant to the SDK, we're concerned with making it easy to use existing Globus services -- this therefore doesn't seem like a great fit. You might be well served by popping off an email to outreach@globus.org describing your use case.

It also might be worthwhile to chat about this on developer-discuss@globus.org (which is meant for stuff like this).

Given that there isn't anything actionable for the SDK on this, I'm going to close it.

---

However, some thoughts before calling it quits...

- Assuming that users will (on purpose or by mistake) violate any fixed schema for data which you set, either (a) all of your tools need to be ready for that or (b) you need to ensure that you aren't trusting users' claims.
  (b) is the easier of the two (after all, what good is a schema if it can be violated...).

- Searchable Globus Endpoint fields are all freely manipulable except for owner.
  Since most of the searchable fields can be written by anyone, and are just text fields, you can't trust endpoint Keywords or Organization values to mean anything. They may still be useful _clues_ about where to look for data, but they aren't verified at all.

- If you want data to be available on demand and durable, you probably need to aggregate it on a central endpoint.
  Globus Connect Personal often represents someone's laptop. Laptops can be offline, Globus Connect Personal could be uninstalled (crazy, I know!), or the machine can be dipped in the nearest liquid nitrogen tank.

- You can't split `find /` across Globus endpoints. This is another reason to centralize things -- I think it will make searching data much easier.
  Globus Transfer doesn't support any `find`-like operations, but even just `ls` on a single endpoint is simpler than searching a disparate (perhaps undefined) set of endpoints, any of which may go offline at any time.

- It sounds like you want to do policy enforcement on the actual data stored on an endpoint. Globus can't do this -- at least not today -- but you might be able to manage it by clever use of the filesystem on an endpoint.
  Imagine this scenario: you have three folders, with different permissions settings (via Globus Sharing ACLs):
  - `RW /writebin`
  - `R /badbin`
  - `R /goodbin`

  You wait for writes to `/writebin` using `inotify` or similar, and then process them with a validator. (Or, easier, you run your validator as a cron job.)
  Well formed docs go to `/goodbin`, malformed docs go to `/badbin`, which gets wiped periodically.
  In this scenario, `/goodbin` only has docs that passed your validation, `/badbin` is only useful for debugging.
