### ISSUE TITLE
programmatic creation of personal endpoints

### ISSUE THREAD

**Issue by vsoch** [globus/globus-sdk-python#271]
I've been writing instructions for users to download the globuspersonalconnect client to create an endpoint for a specific folder, and I think this is reasonable given that they need to open up the browser and log in, etc. However I'm looking for a solution that is many fewer steps than what I'm figuring out to do. I am doing the following:

 - define computer as personal endpoint
 - edit config-paths to limit permissions 
 - edit (something else I haven't found yet) to define a shared folder to be where the images are.

I felt ok about 3 steps, but when I did a list (and then went to the web interface) I saw...

![image](https://user-images.githubusercontent.com/814322/34441695-2f6aabc2-ec72-11e7-8d1f-ce943a4004a2.png)

Absolutely nothing! The reason of course being because the folder is hidden and I'd need to select to show it:

![image](https://user-images.githubusercontent.com/814322/34441704-4b367a7a-ec72-11e7-86ec-d9aeff2f78f8.png)

But I think we can do better than this, because each step that we add on to the flow the more likely it is that the user is going to miss something and find it hard to use. Here is sort of what I'd like to do (and please let me know if this is reasonable).

## Endpoint Setup
The user has some (short) series of steps to set up the endpoint locally. Ideally, we could do this completely programatically (from within python) without needing to install "globuspersonalconnect" and "globus-cli" and still "globus-python-sdk" - that's a ton of dependencies for just this one thing! If I implemented it with the sregistry client, the logic would work as follows:

  1. The user creates the endpoint (or has sregistry do it for him/her) and adds the id to a variable that sregistry can access.
  2. When the client starts, the endpoint is found via the variable, and then the client finishes setting it up. This means **1)** creating a specific share for the sregistry storage folder (if it doesn't exist) and **2)** ensuring that the shared folder is by default not hidden (because by default it is hidden, and if I do a list on my command line I see nothing akin to the web interface.

This series of steps to read in the endpoint id and then check for paths and sharing should be the minimal requirement for setup. You can imagine if something is off the user can be notified immediately, and the functions that the user is given can be determined based on what is found.

Could you point me to the right docs / or make a suggestion about how to best accomplish this? I poked through the python sdk and the online docs but primarily see stuffs related to clients for transfer / server endpoints (as opposed to set up stuffs). Thank you!

**Comment by sirosen** [comment]
Hi @vsoch, I think this one will be an uphill battle. A lot of it we can do; but very little of it is easy.
There's no obvious doc I can send you, so I'll just write things down as best I can.

> edit (something else I haven't found yet) to define a shared folder to be where the images are.

This is the only thing to which I have a "simple" answer -- sharing always needs to pass through a Shared Endpoint, even if it's hosted on a Globus Connect Personal endpoint.
So this is actually a callout to the Globus Transfer API to create a Shared Endpoint (rooted in whatever dir).

> The user has some (short) series of steps to set up the endpoint locally. Ideally, we could do this completely programatically (from within python) without needing to install "globuspersonalconnect" and "globus-cli" and still "globus-python-sdk" - that's a ton of dependencies for just this one thing!

I agree, this is a big hurdle for new users, though we're going to run into several issues trying to simplify.

Some initial reactions
- The `globus-sdk` is never a dependency end-users should see directly. Python programs can include it, and scripts which want to use it should distribute themselves with setuptools (so that they can depend on it). As long as the end-tool is packaged well, this shouldn't matter
- The `globus-cli` is about offering an interface to Globus APIs, and one of the things I love is that everything it does can be done via the SDK (so they dovetail nicely). I'm not _against_ it being integrated with Globus Connect Personal, but I'd have some pretty hefty demands for new/better Globus Connect Personal interfaces, and ideally SDK bindings for those capabilities...
- ...which brings us to Globus Connect Personal. It has a CLI (kinda) of its own under Linux, and different builds for each of the other major two platforms which don't include that CLI.
  - CLI and SDK are both fully cross platform products -- we promise that they work on Windows, Linux, and mac OS hosts. I think the biggest, and first, thing we'd need for CLI<=>Globus Connect Personal integration is a much better, and more uniform, way of controlling it and talking to it locally than disparate config files.
  - Best case, we'd have `globus_sdk.LocalGlobusConnectPersonal` or something which takes care of all of this stuff. Then, adding CLI commands for running it is easy.

I'm really wary of trying to interface with Globus Connect Personal as it currently exists. Across the three major platforms, it has significant differences, and hasn't been designed to be programmable.

> If I implemented it with the sregistry client

Mostly out of curiosity, is the sregistry client Python code?

Shipping `globus-sdk` (or even `globus-cli`) as a dependency is easy for Python. Embedding `globus-cli` to act as an interface for a non-Python language... although it would ideally work out, it's likely really hard.

> 1. The user creates the endpoint (or has sregistry do it for him/her) and adds the id to a variable that sregistry can access.

Okay, so there are actually multiple parts to this.

The first, creating an endpoint, itself consists of installing Globus Connect Personal and running the setup or starting the application. I think those steps are doable from your code if you're on Linux (and perhaps you don't care about the other platforms).
The setup command will consume a setup key -- you could direct users to the www.globus.org/app application for this. If you wanted to handle it for them, either the user needs to sign in (via Globus Auth) to an application which you control, or you need to have them `globus login` and then you can `globus endpoint create --personal ...` to get a setup key.

When you want to get the resulting endpoint ID back out, that's one of the few easy/doable things. We actually have an open issue [cli#371](https://github.com/globus/globus-cli/issues/371) for adding this functionality to the CLI (and maybe the SDK too). The issue describes where you could look for yourself for now.

> creating a specific share for the sregistry storage folder (if it doesn't exist)

I'm not sure how you'd do this 100% unambiguously, but there's probably a workable 80% solution if you do an Endpoint Search and filter down to shared endpoints with the desired Globus Connect Personal endpoint as a host endpoint.
See the [valid params to endpoint_search](https://docs.globus.org/api/transfer/endpoint_search/#endpoint_search) for more details.

> ensuring that the shared folder is by default not hidden (because by default it is hidden, and if I do a list on my command line I see nothing akin to the web interface.

This is a characteristic of every `ls` request made to the Transfer API -- there's a parameter for `show_hidden` which can be used to control whether or not dotfiles (those starting with `.`) are displayed.
In the CLI, it's a matter of `globus ls --all`, and in the web interface you need to select the menu option.

Wanting to create a folder whose name starts with `.`, but then wanting to ensure that it is visible, strikes me as very niche -- since it countervails the typical meaning and use of dotfiles.

Is there another solution open to you? Perhaps creating a symlink `singularity -> .signularity`?

**Comment by sirosen** [comment]
There's now an SDK method for getting the local Globus Connect Personal endpoint ID, [released in v1.5.0](https://github.com/globus/globus-sdk-python/releases/tag/1.5.0).

Since there's nothing more that the SDK can do for now, I'm going to close this.

I'd like to see more functionality out of Globus Connect Personal to support this use case, but I don't want tracking for that in this repo.

**Comment by vsoch** [comment]
Thanks @sirosen for your work on this ! I will make note of this and give the SDK method a try.
