### ISSUE TITLE
SDK Version 1.4.1 DataPublicationClient broken check for GLOBUS_SDK_ENVIRONMENT

### ISSUE THREAD

**Issue by dnarc** [globus/globus-sdk-python#272]
Python version: 3.4
Globus SDK Version: 1.4.1

Error:

pub_client = DataPublicationClient(base_url, authorizer=pub_authorizer)#012  File   self.base_url = config.get_service_url(environment, service)#012  File "/usr/local/lib/python3.4/dist-packages/globus_sdk/config.py", line 140, in get_service_url#012    .format(service, environment))#012ValueError: Failed to find a url for service "datapublication" in environment "default". Please double-check that GLOBUS_SDK_ENVIRONMENT is set correctly, or not set at all

---
This call is in code that works on SDK version 1.2 and I am not explicitly setting GLOBUS_SDK_ENVIRONMENT anywhere.

**Comment by sirosen** [comment]
Hi @dnarc, `DataPublicationClient` isn't a part of the Globus SDK. Is it an SDK-like client class which you are maintaining?

If I had to guess, I'd say that `DataPublicationClient` is probably relying on an undefined behavior which has been _improved_ to be an error (yes, there is an element of irony to that). Namely, #247 (released in v1.3.0) fixes the fact that unmatched/invalid service names would give clients a `None` URL, and an error at use-time (vs instantiation time).

The fix, luckily, is simple: as of v1.2.2 all clients accept `base_url` as a keyword argument, which lets you programatically set the URL for a client.

If you need further help tracking this down and applying the fix, I'm happy to discuss further here or via support@globus.org , but since this is not an SDK bug I'm going to close.
