### ISSUE TITLE
Creating directories along with their parents

### ISSUE THREAD

**Issue by papajim** [globus/globus-sdk-python#273]
Hello,

I've been trying to find a way to create a directory with its parent directories, in case they are missing.

My first thought was to use "operation_mkdir" of the TransferClient, but there is no option for creating parent directories (https://docs.globus.org/api/transfer/file_operations/#make_directory).
Another way could be via doing a dummy transfer with same source and destination, because a transfer task creates parent directories. For example I was thinking to do a transfer from "/dev/null" to ".dummy". However access to /dev/null is prohibited at some endpoints (eg. NERSC-DTN).
The last thing that comes to mind, is to loop over the path and create the parent directories one by one with "operation_mkdir". However this is too naive and slow. There should be another way...

Is there a designated way of creating directories along with their parents, when they don't exist?

Thanks,
George

**Comment by sirosen** [comment]
As far as I know, there is no other way _currently_.
However, I think there probably should be one.

> Another way could be via doing a dummy transfer with same source and destination, because a transfer task creates parent directories.

This is an interesting point. I took a look through the way we make these directories, and if I'm reading it right we're actually doing the simple loop over parent directories.
However, since it's happening just between Globus and the endpoint -- leaving out the overhead of multiple requests -- it's much faster than trying to do this with `mkdir` calls to the API.

As far as I know, GridFTP doesn't support a `mkdir -p` equivalent, so there's no simple fix.
We could expose the (reasonably fast) recursive mkdir operation through the Transfer API, but it probably isn't trivial -- at the very least, it could be slow enough when given very long paths which blocks and eventually times out. I'll open this up for discussion with the Transfer API team.

> For example I was thinking to do a transfer from "/dev/null" to ".dummy". However access to /dev/null is prohibited at some endpoints (eg. NERSC-DTN).

You could move an empty file to `.../.dummy` without using `/dev/null`, since most endpoints will disallow access to `/dev/`.
i.e. Your approach works, so long as you use a normal empty file.

---

Given that there is no viable work item against the SDK to derive from this feature request, I'm going to close this issue. However, I'll comment on it further if I get interesting info from discussing this with the Transfer API team.
