### ISSUE TITLE
2 factor authentication flow

### ISSUE THREAD

**Issue by vsoch** [globus/globus-sdk-python#286]
Hey Globus! 

Let's say I start with my Native Application, where the user is authenticated via refresh tokens with globus, so they can do things like search and find endpoints:

![image](https://user-images.githubusercontent.com/814322/38572784-1766cdb2-3cc2-11e8-8d3a-509b64e0f347.png)

For a while I couldn't figure out why all of them were inactive (absence of green active) but then when I went to the globus portal, and did two factor auth there, sherlock became active! (see the little green square!). This is the purpose of having this search - I can now click on the exposed link and see the files there.

The question that I have is how this activation can happen easily, ideally from this interface, without some weird workflow like needing to go to globus.org first.  Given that the information that I have about an endpoint, for example, Sherlock cluster, has these fields:

```
{'DATA_TYPE': 'endpoint',
 '_rank': 1.48634168505669,
 'acl_available': False,
 'acl_editable': False,
 'activated': True,
 'canonical_name': 'srcc#sherlock',
 'contact_email': 'research-computing-support@stanford.edu',
 'contact_info': '',
 'default_directory': '/~/',
 'department': 'SRCC',
 'description': 'Stanford Research Computing Center - Sherlock',
 'disable_verify': False,
 'display_name': 'SRCC Sherlock',
 'expire_time': '2018-04-20T17:08:55+00:00',
 'expires_in': 863800,
 'force_encryption': False,
 'gcp_connected': None,
 'gcp_paused': None,
 'globus_connect_setup_key': None,
 'host_endpoint': None,
 'host_endpoint_display_name': None,
 'host_endpoint_id': None,
 'host_path': None,
 'https_server': None,
 'id': '6881ae2e-db26-11e5-9772-22000b9da45e',
 'in_use': False,
 'info_link': 'http://www.sherlock.stanford.edu/docs/user-guide/data-transfer/#globus',
 'is_globus_connect': False,
 'is_go_storage': False,
 'keywords': '',
 'local_user_info_available': True,
 'location': 'Automatic',
 'max_concurrency': 4,
 'max_parallelism': 8,
 'my_effective_roles': [],
 'myproxy_dn': None,
 'myproxy_server': None,
 'name': 'sherlock',
 'network_use': 'normal',
 'non_functional': False,
 'oauth_server': 'cilogon.org',
 'organization': 'Stanford University',
 'owner_id': 'c3a37540-d274-11e5-b5f9-3304ce16df55',
 'owner_string': 'srcc@globusid.org',
 'preferred_concurrency': 2,
 'preferred_parallelism': 4,
 'public': True,
 's3_owner_activated': False,
 's3_url': None,
 'shareable': True,
 'sharing_target_endpoint': None,
 'sharing_target_root_path': None,
 'storage_type': None,
 'subscription_id': '393da453-bd08-11e4-add0-22000a97197b',
 'username': 'srcc'}
```

How do we parse / use this to do the following:

 - determine if the user has an ability, period, to authenticate to use the endpoint
 - determine if the user can (without extra work) do this. Right now I think the field "activated" as False would mean both "I can't connect to it without further authentication" but also "I can't connect period because I'm not a user of this resource." We would want to untangle those two things.
 - If the user can (one of the booleans above) provide a link that can take them through two factor (or other custom auth) under the same page control (so not need to open globus.org unless it's a nice redirect).

I see the `oauth_server` variable, but I'm not sure I can use that just on its own for anything.

I'll keep poking around the docs, but I am a bit lost in the wilderness again! Thanks for your help!

**Comment by sirosen** [comment]
These are the answers I can provide:

> determine if the user has an ability, period, to authenticate to use the endpoint

This cannot be known until the user attempts activation.
Consider an endpoint with the simplest myproxy server setup to use local accounts with password auth.

I may be `sirosen@globus.org` as far as Globus and your application are concerned, but my account on the endpoint may be `stephen` with password `abc123!`.
Until I attempt myproxy activation and provide my local username and password, the Globus Transfer API cannot know whether or not I, the human user, have credentials to use that endpoint.

To varying degrees, that same model applies to the other activation types.

> determine if the user can (without extra work) do this. Right now I think the field "activated" as False would mean both "I can't connect to it without further authentication" but also "I can't connect period because I'm not a user of this resource." We would want to untangle those two things.

The `activated: False` field just tells you whether or not the endpoint is currently activated. It contains and implies no further information.

It is documented, along with the other endpoint document fields, here:
https://docs.globus.org/api/transfer/endpoint/

The Transfer API does not have any notion of who is allowed to use different endpoints beyond the various current activations which may be in effect.
If we want to go a layer deeper, it doesn't even know if the credentials from an endpoint are valid until it attempts to do a filesystem operation -- a misconfigured endpoint could be activated, but totally broken.

"I can't connect to it without further authentication" therefore describes *all endpoints at all times*, and we can't, as users of the API, know anything more than that.

> If the user can (one of the booleans above) provide a link that can take them through two factor (or other custom auth) under the same page control (so not need to open globus.org unless it's a nice redirect).

This is going to depend a lot on how much work you want to do to support different activation flows within your application.

You can build out code to do all of the different types of endpoint activation, but there's an awful lot of it.
You would need to decide which of the [available activation types](https://docs.globus.org/api/transfer/endpoint_activation/#activation_types) you want to support.

The easiest way is to send the user to
```
"https://www.globus.org/app/endpoints/{}/activate".format(endpoint_id)
```
in a new tab and let them activate there.

The Globus WebApp handles various activation cases including the [OAuth MyProxy](https://docs.globus.org/api/transfer/endpoint_activation/#oauth_myproxy) case, which is one of the more secure options.

It should be technically possible for you to implement OAuth MyProxy activation yourself, but
- That method isn't publicly documented. You would do best to submit a question at support@globus.org if you wanted to find out how.
  Adding documentation for it wouldn't be a bad call, but I don't know how easy it would be to completely and accurately document, especially since it may depend on the versions and behaviors of the OAuth server in use on the endpoint.
- Gut call: it's probably a lot of work. Redirecting to `www.globus.org/app/endpoints/<id>/activate` is easy and basically foolproof.

---

Final thought: autoactivation.

As a general practice, most applications attempt autoactivation before even moving on to other activation types.
Autoactivation covers the endpoint configurations in which the endpoint trusts the Globus Transfer service and has some mapping from Globus accounts to local user accounts.

To steal a snippet from the Globus CLI,
```
# client is a globus_sdk.TransferClient
res = client.endpoint_autoactivate(endpoint_id, if_expires_in=60)

if "AlreadyActivated" == res["code"]:
    formatted_print(res, simple_text=(
        "Endpoint is already activated. Activation "
        "expires at {}".format(res["expire_time"])))
    return
```

The Globus Tutorial endpoints all respond to autoactivation, if you want a test case.

A good starting point (and arguably a good stopping point) for an application is to attempt autoactivation and then, if that fails, redirect users to the Globus Webapp.
It may require an extra authentication step for users to login there, but the end result will likely be more reliable than any alternative.

If you have further questions that aren't tied to specific pieces of SDK functionality, I would recommend asking them at support@globus.org, as activation is a fairly expansive topic. Questions or issues with the activation, autoactivation, and get_activation_requirements functionality provided by the SDK's TransferClient, of course, belong here.

**Comment by vsoch** [comment]
hey @sirosen ! The external link to activate via the globus portal was perfect, I didn't mean to say that it was bad or anything like that. I am able to direct the user to the page, and when they come back, a link is exposed to have them click again on the link for the endpoint they want:

![image](https://user-images.githubusercontent.com/814322/38599416-7af475ac-3d2e-11e8-9501-a21fb65517da.png)

I'm definitely most comfortable putting the user in control, and so my preference is not to even use any autoactivation. If an endpoint is to be made active, I want it a decision of the user. I can ask this where directly is relevant, but I wonder if the term/variable activated could be misleading because it really doesn't tell us much information about the state of the node, only that we don't know until we are logged in. I would say that:

 - if a user is not authenticated, the `activated` variable should be unknown or None, and not activated False that implies it's not activated (for example, all three of the endpoints above *were* active but returned as activated False in the initial queries. It's not wrong to say this given that I don't have the permissions, but I think most users/developers looking at the metadata could easily think that the endpoint isn't in fact activated (and email some cluster admin and complain, etc.)
 - OR separate out the variable activated into two - activated and something along the lines of viewable / seeable / accessible. An endpoint could then have all of these states:
  - activated and accessible (show the green success box above)
  - activated but not accessible (cue the link you showed me above)
  - not activated and not accessible (I wouldn't give them any link here, saving a lot of clicks)
  - not activated and accessible (this would be where contacted the cluster admin is relevant).

Is this revealing too much information? Given that we don't know about user accounts, I would minimally change the state of "not activated" to something that says "we don't know" and then require the user to click and discover :)

Thanks for your help! Your feedback did resolve my issue, so retrospectively the close is +1 from me.

**Comment by sirosen** [comment]
I think you're seeing and responding to the fact that the activation model we have is confusing. Which it is. I wouldn't try to pretend otherwise.

We know we need to completely redesign activation at some point in order to fix it or at least make it simpler, but it's a pretty difficult task. I don't know / can't tell when we'll be able to address it.

> three of the endpoints above were active but returned as activated False in the initial queries

This sounds like you're conflating endpoint activation -- the binding of a credential for a specific user to a specific endpoint -- with the existence/validity of an endpoint.

The Transfer service has no notion of an endpoint being valid or invalid, functional or broken.
Both the service used for activation and the GridFTP servers which handle data transfers and filesystem interactions are only known to work or fail at the time that a user tries to use them.

Knowing that an endpoint is correctly configured and operational is a more nuanced and treacherous road than it may at first appear. The API avoids presenting misleading or stale information by following an EAFP design.

---

If I were to recommend a way of presenting this information to users, it would be to follow the lead of the Globus web app. Our current view for an [endpoint search](https://www.globus.org/app/endpoints) has columns like so:
![image](https://user-images.githubusercontent.com/1300022/38620792-70afe65a-3d6d-11e8-8ad7-e82a8b9d92c0.png)
![image](https://user-images.githubusercontent.com/1300022/38620757-5d8a507e-3d6d-11e8-9fd4-725b2103f7b0.png)

These columns are primarily populated from the `activated` and `expires_in` fields of the endpoint documents.
"setup incomplete" is an interesting status produced from `is_globus_connect` (the endpoint is a Globus Connect Personal installation) and `globus_connect_setup_key` being non-null.


Though you may choose different phrasing, stating that an endpoint is "not activated" hasn't generated much user confusion for us, anecdotally.

To hypothesize a little bit: most users probably assume that everything they're being shown is valid/works. Pairing the activation status, "not active", with some kind of actionable response, the "activate" link, is probably worth imitating because it reinforces that thinking.

**Comment by vsoch** [comment]
hey @sirosen I will definitely use the same convention. A quick follow up - you said that:

> "setup incomplete" is an interesting status produced from is_globus_connect (the endpoint is a Globus Connect Personal installation) and globus_connect_setup_key being non-null.

I'm looking at our Stanford endpoints (not Globus connect) and they have `is_globus_connect` as False (I would expect this) but then I'm also looking at endpoints I know are personal and they also have `is_globus_connect` as False (unless it's activated, then there is a True of course). I'm not seeing null values anywhere to say "this is not a Globus Connect Personal Installation). Do you have pseudocode (or actual) you could share to generate the groupings above?

**Comment by sirosen** [comment]
Noticed I missed this follow-up.

> Do you have pseudocode (or actual) you could share to generate the groupings above?

I don't, and I'm sufficiently non-expert in production-quality JS code that I don't think I can easily extract it from the Globus webapp.
Your best bet for getting a real answer is to ask support@globus.org and say explicitly that you want to imitate the categorization done by "www.globus.org/app/endpoints" (so our support staff can route your question correctly).

>  I'm also looking at endpoints I know are personal and they also have `is_globus_connect` as False

That's surprising to me. In my experience, that flag has been fairly reliable as a determinant of the endpoint type, but perhaps there are subtle corner cases. Again, the Globus webapp developers would probably have the best and most authoritative information on how that might be possible -- they actively work with and have to handle _all_ of the odd corner cases.

For the purposes of labeling not-yet-setup personal endpoints, relying on `globus_connect_setup_key` having a non-null value should be sufficient. That field will be present and null on any endpoint which is not a Globus Connect Personal endpoint.

**Comment by vsoch** [comment]
> Noticed I missed this follow-up.

No worries!

> I don't, and I'm sufficiently non-expert in production-quality JS code that I don't think I can easily extract it from the Globus webapp.

haha, me too! Actually one of the reasons I don't use a lot of the fancy / trendy front end UIs is because they tend to bundle everything. It's fine if you have the source, know what you are doing, and can re-bundle, but usually 1) I don't have the source off hand, 2) I can't keep up with the trending JS libraries, and 3) if a collaborator had the source anyway, it would probably still be a heavy learning curve for Angular / React / Vue.js / etc. to contribute meaningful.  TLDR: Vanilla Javascript and JQuery ftw!

> Your best bet for getting a real answer is to ask support@globus.org and say explicitly that you want to imitate the categorization done by "www.globus.org/app/endpoints" (so our support staff can route your question correctly).

Done!

> That's surprising to me. In my experience, that flag has been fairly reliable as a determinant of the endpoint type, but perhaps there are subtle corner cases. Again, the Globus webapp developers would probably have the best and most authoritative information on how that might be possible -- they actively work with and have to handle all of the odd corner cases.

It's probably just a bug somewhere :bug: 

thanks again
