### ISSUE TITLE
OAuth2 Error after sdk update

### ISSUE THREAD

**Issue by ghltshubh** [globus/globus-sdk-python#312]
I am unable to login to hosted globus data portal app. I was able to yesterday.

Unable to Fulfill Your Request
Error processing OAuth2 request
Sorry, but we encountered a problem while servicing your request.

Mismatching redirect URI.
Occurred at time:
2018-08-30T21:02:23.213044+00:00
Error ID:
fdc11b88-ac97-11e8-b444-0e9a30df9590
Error code:
OAUTH_AUTH_REQUEST_FAILURE

**Comment by jaswilli** [comment]
Hi @ghltshubh,

Sorry you're having trouble logging in. I don't think this is related to the recent SDK release (I don't think `mrdp.globus.org` has probably even updated to use the latest yet).

That said, I am able to successfully log into the hosted sample data portal. Can you try again and see if it's still happening (preferably in an incognito window)? Perhaps it was a temporary problem.

I'm going to close this since it's not directly related to the SDK but please reply and let me know either way if it's working or not.

**Comment by ghltshubh** [comment]
No @jaswilli I tried installing the one that's available on github https://github.com/globus/globus-sample-data-portal
on my server and it is giving not just me but everyone who tried to login that OAuth error today which it wasn't yesterday.

**Comment by jaswilli** [comment]
Okay, when you said "hosted" above I mistakenly thought you were referring to the hosted sample data portal that we run and have linked from our web site.

If you installed a copy of the sample data portal repository and are hosting it somewhere on the internet it will not work unless you have registered your own "App" (https://developers.globus.org) and configured it with the correct redirect URI for the domain you have it hosted on. The instructions can be found here: https://github.com/globus/globus-sample-data-portal#create-your-own-app-registration-for-use-in-the-portal

The error message you provided above is "Mismatching redirect URI" which means that Globus Auth is refusing to issue the redirect back to the application because the provided URL has not been registered. It's a security measure. If follow the instructions I linked above it should start working.

Let me know if you have any more trouble.
