### ISSUE TITLE
pyfilesystem interface for globus

### ISSUE THREAD

**Issue by rabernat** [globus/globus-sdk-python#317]
I am a globus user. I mostly use the service in interactive mode via the web. But in the [pangeo project](http://pangeo.io), we are exploring different ways of working lazily with distributed storage.

[pyfilesystem](https://www.pyfilesystem.org/) is a Python module that provides a common interface to any filesystem. There are [implementations](https://www.pyfilesystem.org/page/index-of-filesystems/) for a wide range of local and remote storage protocols, including FTP, SSH, dropbox, etc.

A pyfilesystem interface for globus would allow other projects to start using globus more easily, without having to use the somewhat unfamiliar globus sdk. Is this on your radar? What do you think about the likelihood of implementing something like this?

**Comment by sirosen** [comment]
It's unlikely that we would pursue this, at least given the current landscape for Globus. Not because we hate good interfaces, but simply because (1) I don't think we can commit to supporting something like this and (2) the performance characteristics and behaviors would be quite unfavorable.

After looking at a couple of pyfilesystem implementations for a couple of minutes, I can say with some confidence that we'd have significant issues. Credential handling is a big one. Because Globus authorization is always done via OAuth2 Clients, you need to think about when and how user login happens, how you pass those credentials through to the "filesystem" adapter, and how you handle token expiration. Additionally, you have to handle authentication against endpoints -- the Activation step -- which can expire or be revoked in the middle of data transfers, and doing a Transfer to your local filesystem requires that the local FS is a Globus Endpoint, and that Globus Connect Personal (or Server) is able to write to a known directory for sharing data to the filesystem-like abstraction layer.

I've seen a couple of people try doing proof of concept FUSE filesystem adapters and they almost always suffer significant performance issues -- beyond those of FTP, S3, or other remote filesystem-like storage services. Reading a remote file through Globus Transfer is not a simple matter of pulling data in as fast as your pipes can handle it. Especially in the case of many small read operations, you'll find issues with the fact that pulling in files requires submitting a task, waiting for it to execute, and then reading the results from the local filesystem. Even `ls`, `mkdir`, and `mv` pass through the Globus Transfer service, which increases latency (even when the remote system is on your local network), and gives you a central bottleneck.
Unless we change the architecture for Endpoint interactions really significantly (and there are some steps towards this that we're working on with the new version of Globus Connect Server), there's no way to get good performance without aggressive caching and weak guarantees around write consistency with the remote endpoint.

We've tried to strike a balance in the SDK in terms of complexity to use and complexity to support, and this seems like something great to use, but burdensome for us to commit to supporting.

Long term, if we can cut down on the complexity of auth and credential handling for developers, and someday have viable python or C libraries for doing GridFTP operations directly against Endpoints (importantly, this would allow you to avoid a requirement for a local, activated Endpoint), we might be able to pursue even higher levels of abstraction on top of the SDK.
Because higher level abstractions inherit the limitations of the layers they build upon, there's a significant gap for us to cover before it's wise for us to pursue more advanced capabilities than what the SDK offers today.
