### ISSUE TITLE
Make a user searchable by globus username/email after AuthClient login

### ISSUE THREAD

**Issue by yuanzhou** [globus/globus-sdk-python#368]
We are developing some apps with Globus and using its groups access features. For adding new users to the group, we can get the user's globus username by parsing the `preferred_username` field using the `AuthClient`. However, the user has to manually login "https://app.globus.org/" in order to make this user searchable by username/email on our group admin end to add new user.

Is there a way to make the user searchable without asking the user to manually login?

**Comment by sirosen** [comment]
Hi, sorry for leaving this for so long. It got lost in the shuffle a bit.

Unfortunately, I don't think that users are searchable until they've interacted certain parts of the groups service. There are historical reasons for this, but from a user-perspective, they really don't matter.

There's not much we can do about this in the SDK itself. If you file a change request / feature request about this via `support@globus.org` or on our mailing lists, I can make sure that the right members of our team get looped in. (Feel free to refer back to this issue.)

I just tested, and the new Groups API does not resolve this issue (there isn't SDK support for the groups service yet anyway).

We can, however, solve the problem with a bit of a workaround.
If you have your app interact with the Globus Transfer service on behalf of the user, it will force an interaction between the services which makes the user searchable.
For example, if the user signs in to the globus CLI and runs `globus ls`, they will become searchable even if the `ls` call fails.

The reason is that Globus Transfer, like our web app, interacts upstream with the groups service in the correct way.
I can't promise that this workaround will last long-term, but it may be a viable band-aid for now.


I'm going to close this, not because your issue is resolved, but because, unfortunately, there's nothing we can do in the SDK itself for this case. It would be better to follow up via another forum, as I mentioned above.

**Comment by yuanzhou** [comment]
Understood, thank you for your detailed reply!
