### ISSUE TITLE
automate sharing?

### ISSUE THREAD

**Issue by jasonsydes** [globus/globus-sdk-python#401]
Hello there Globus community!

I've been working with the python SDK, and have integrated some internal file/folder transfers into our workflow.  That part is working great.

We perform DNA sequencing for customers, and some of our customers would like us to provide them with their data via Globus (these data do get pretty large, and transferring them over HTTPS is much slower than Globus). We'd like to be able to setup sharing automatically.  Unfortunately, I cannot seem to find that as a feature of the python SDK, though I've certainly been looking all over for it.  Apologies if it does exist and I wasn't able to find it.

I do believe that this functionality is present in the Globus CLI, as I was able to successfully share a folder with (roughly) the following command:
```
globus endpoint permission create --permissions r --notify-email fake@email.address --notify-message "we did it" --identity testjason4@globusid.org ee2efe96-f539-11ea-8928-0a5521ff3f4b:/labs/FAKE7
```
First off, am I doing the above correctly (if not, should I be doing something differently?).

And second, is this functionality present in the Globus SDK?

Thank you very much for your time and assistance!

PS - Our university has a license for Globus Connect Server.

**Comment by sirosen** [comment]
Hi there! `permission create` with `--permissions r` sounds to me like the right command for what you're trying to do -- although obviously I don't know everything about your use-case.

The functionality is definitely available in the SDK. We use the SDK extensively to implement the CLI, and only very rarely rely on features which are not present in the SDK.

The names, however, are somewhat different in the SDK. I think we we chose `permission` because it's a bit nicer for new users, but the underlying entity is an "access rule" which goes in an "access control list" (acl). The method you most likely want is [`TransferClient.add_endpoint_acl_rule`](https://globus-sdk-python.readthedocs.io/en/stable/clients/transfer.html#globus_sdk.TransferClient.add_endpoint_acl_rule).

If you crack open the source for the CLI, you'll actually be able to find [that the CLI is calling precisely this function](https://github.com/globus/globus-cli/blob/6bac40433541888877b597fdbb041c21f261fb66/globus_cli/commands/endpoint/permission/create.py#L95).

I should also note that the Transfer API does not expect usernames of the `username@domain` format, but the underlying identity IDs. As a result, when using `add_endpoint_acl_rule`, you'll want to lookup usernames before calling this method.
In the CLI, this is solved with a call to [`AuthClient.get_identities`](https://globus-sdk-python.readthedocs.io/en/stable/clients/auth.html#globus_sdk.AuthClient.get_identities).

I'll also point you at the [`IdentityMap`](https://globus-sdk-python.readthedocs.io/en/stable/clients/auth.html#helper-objects) helper object we provide in the SDK. It keeps a cache of past lookups, so multiple lookups for `foo@example.com` would only need to make one network call. Plus, it automatically detects usernames (`user@domain`) vs identity IDs and looks them up appropriately.

Generally, I would recommend that you create an `IdentityMap` for lookups just to take advantage of the friendlier interface. But if you are handling a username for a user who has not logged in to any Globus services yet, equivalent to the `--provision-identity` option to `permission create`, you may need to use `AuthClient.get_identities(..., provision=True)`.

I'm going to close this, as I think the question is pretty open-and-shut (yes, we do support that feature!), but we can certainly discuss this further if you have related questions or think there's some way we can improve the docs.

**Comment by jasonsydes** [comment]
@sirosen, this is so helpful! Well beyond what I asked. Thank you so much!

**Comment by jasonsydes** [comment]
Hello again! I finally have time to implement this, but I'm running into problems. I'm not sure if @sirosen would be able to assist again, or someone else?

I've been using Globus in production for quite awhile now (over a year at least, maybe two?). When I was getting things setup over a year ago, I headed over to https://auth.globus.org/v2/web/developers and setup "gc3f-globus-non-native-app" (client id "ce1fbae4-ea1c-4031-817b-64d7ab29d1f0"), a "non-native app" (Required Identity is blank,  Pre-select Identity Provider is blank, and the Redirect URLs is "https://auth.globus.org/v2/web/auth-code", which apparently you can't do anymore?). I copied down the secret, and my tools load it up as described here:

https://globus-sdk-python.readthedocs.io/en/latest/examples/client_credentials.html#do-the-flow
and here:
https://globus-sdk-python.readthedocs.io/en/latest/examples/client_credentials.html#do-the-flow

I know it's "working", because I'm able to do all of the following things:

tc.endpoint_search(filter_scope="shared-with-me"):
tc.operation_ls(ep_id, path=path)
tc.operation_mkdir(ep_id, path=curr_dir)
tc.operation_rename(ep_id, oldpath=old_path, newpath=new_path)
globus_sdk.DeleteData(tc, ep_id, label=label, ...
tc.endpoint_autoactivate(ep_id)
delete_result = tc.submit_delete(ddata)
globus_sdk.TransferData(tc, src_ep_id, dest_ep_id, label=label ...
tc.endpoint_autoactivate(src_ep_id)
tc.endpoint_autoactivate(dest_ep_id)
tc.submit_transfer(tdata)
tc.task_wait(task_id, timeout=timeout, polling_interval=polling_interval)
tc.get_task(task_id)
tc.task_list(num_results=20, filter=filter)
tc.cancel_task(task_id)

However, when I try to do call tc.add_endpoint_acl_rule I get a PermissionDenied error.
```
  File "/my_globus_tool.py", line 163, in go
    res = self.tc.add_endpoint_acl_rule(endpoint_id, rule_data)
  File "/globus-sdk-fun/lib/python3.10/site-packages/globus_sdk/services/transfer/client.py", line 873, in add_endpoint_acl_rule
    return self.post(f"endpoint/{endpoint_id}/access", data=rule_data)
  File "/globus-sdk-fun/lib/python3.10/site-packages/globus_sdk/client.py", line 153, in post
    return self.request(
  File "/globus-sdk-fun/lib/python3.10/site-packages/globus_sdk/client.py", line 298, in request
    raise self.error_class(r)
globus_sdk.services.transfer.errors.TransferAPIError: ('POST', 'https://transfer.api.globus.org/v0.10/endpoint/ee2efe96-f539-11ea-8928-0a5521ff3f4b/access', 'Bearer', 403, 'PermissionDenied', 'Not authorized for the endpoint UO GC3F Globus Share (ee2efe96-f539-11ea-8928-0a5521ff3f4b)', 'wcnBbuPPa')
```
So I installed globus-cli, and started hacking around with this file (thanks @sirosen for pointing me to it): 
https://github.com/globus/globus-cli/blob/main/src/globus_cli/commands/endpoint/permission/create.py
I am able to use our gc3f@uoregon.edu globus credentials (the same account that I am trying to use in the globus-sdk) with the globus-cli with the following command, and it works just fine:
```
Message: Access rule created successfully.
Rule ID: 867e2f2e-b2c0-11ec-b87e-3912f602f346
```
I got that message from running this command:
```
globus endpoint permission create --permissions r --notify-email my@email.com --notify-message "we did it" --identity testjason4@globusid.org ee2efe96-f539-11ea-8928-0a5521ff3f4b:/test3/
```
I hacked the globus_cli/commands/endpoint/permission/create.py code so that it prints out the "rule_data", and it's identical to the rule_data that I'm using when I try to do add_endpoint_acl_rule with globus-sdk. Looks like this:
```
rule_data={'DATA_TYPE': 'access', 'permissions': 'r', 'principal': 'd2266551-6c75-4c77-99ef-e3bf01f105fa', 'principal_type': 'identity', 'path': '/test3/', 'notify_email': 'my@email.com', 'notify_message': 'we did it'}
```
I've poked and prodded around in the code for awhile now, but I'm at a loss. Everything seems identical between my use of globus-cli and globus-sdk, but obviously it's not, as it works for me for the former but not the latter.

Why would all the other TransferClient operations work for me (e.g., operation_mkdir, endpoint_search, operation_rename, etc) in my use of the globus-sdk, but not add_endpoint_acl_rule?  Is this a bug? Probably not, probably I'm just doing something wrong. I just have no idea what it is. Maybe the way I've registered my non-native app with Globus is incorrect? I'm grasping at straws... Any assistance or advice you could provide would be greatly appreciated.

Sincerely,
Perplexed

**Comment by jasonsydes** [comment]
For anyone in the future stumbling across this... I finally figured it out.... The "non-native app" is actually a different user. Our "gc3f@uoregon.edu" user is the administrator of our shared endpoint, and I had used this user to create our "non-native app" user.  For normal activities (e.g., tc.submit_transfer(tdata)) the "non-native app" user worked fine. However, the normal privileges associated with a freshly created "non-native app" user are insufficient for the add_endpoint_acl_rule() method (it needs "administrator" or "access_manager" privileges, see the link below). To fix this, I used my gc3f@uoregon.edu user via the Globus web interface to give my "non-native app" user "administrator" privileges (I think I tried "access_manager" privileges, but that didn't work IIRC).

See:
- https://globus-sdk-python.readthedocs.io/en/1.x-line/clients/transfer.html#globus_sdk.TransferClient.add_endpoint_acl_rule
- https://docs.globus.org/api/transfer/acl/#rest_access_create

**Comment by sirosen** [comment]
I wanted to mention that I saw this in the past, but it fell off my radar to reply. It sounds like as of last week you have the issue figured out. I am sorry that I didn't get back to you earlier, but the initial notification got lost.

I would generally recommend opening a new issue or contacting us via `support@globus.org` rather than commenting on a closed issue. If it's more appropriate to the case, reopening the issue (e.g. we thought we fixed something, but it's still broken) also works.
The reason I mention this is that commenting on a closed issue only notifies one person (in this case, me! and like I said, I am sorry I didn't get you a reply), whereas a new issue, reopened issue, or support ticket notifies our team and has higher visibility.

This also seems like the sort of case which might benefit from being shared on our discussion listhost discuss@globus.org . You can signup [here](https://www.globus.org/mailing-lists). The advantage there is that sometimes a user with a similar use-case can share their solution faster than our team can get back to you.

This isn't meant as an excuse so much as an explanation. We should always reply to user questions. But I wanted to explain that this wasn't visible to our broader team, and offer some recommendations for making sure this doesn't happen again.

**Comment by jasonsydes** [comment]
Hi again Stephen, 
That's definitely good advice on not writing to a closed ticket... Honestly though, I sort of wrote there on purpose, as I was floundering a bit, but suspected I might eventually come across a solution eventually...  if I didn't, I would've opened up a fresh ticket...

But yes, I think I've got all things Globus solved in my system (at least for now). I think my main problem was just that I had so many Globus accounts that they obstructed and confused me from identifying the one account where I actually could assign permissions.

Some helpful associates at my institution helped guide me in for a nice landing, and I eventually saw my error.

In any case, things are working great now, and I've got a second draft of automation using the Globus Python SDK, and it seems to be working well.

I will definitely join the Globus discussion list, I think you're right that I'll benefit. Didn't realize there was one... thanks for this tip!

Thanks again for all your help, and have a great weekend!
