### ISSUE TITLE
TransferAPIError: Error communicating with Globus Nexus Service

### ISSUE THREAD

**Issue by WardLT** [globus/globus-sdk-python#505]
I've run into a few problems when making transfers lately that all have error messages relating to the globus nexus service.

For example:

```
  File "/home/lward/exalearn/edw/env/lib/python3.8/site-packages/globus_sdk/transfer/data.py", line 155, in __init__
    submission_id or transfer_client.get_submission_id()["value"]
  File "/home/lward/exalearn/edw/env/lib/python3.8/site-packages/globus_sdk/transfer/client.py", line 1060, in get_submission_id
    return self.get("submission_id", params=params)
  File "/home/lward/exalearn/edw/env/lib/python3.8/site-packages/globus_sdk/base.py", line 212, in get
    return self._request(
  File "/home/lward/exalearn/edw/env/lib/python3.8/site-packages/globus_sdk/base.py", line 497, in _request
    raise self.error_class(r)
globus_sdk.exc.TransferAPIError: (500, 'InternalError', 'Error communicating with globus nexus service (status=502) (utctime=2022-01-22T18:24:10.474846)', 'gEExD5c1X')
```

Anything I could do to help debug it?

**Comment by sirosen** [comment]
First, I'll state for the record that the SDK is behaving correctly in this case. The Transfer service encountered an error, and this is how it's presented. I think you're aware of this, but want to mention it up-front.
If you see this error, it means that something went wrong in the service.

The last line of the trace would be potentially useful to the service team. Specifically, to pick it apart, it shows the following fields:
```
globus_sdk.exc.TransferAPIError: (500, 'InternalError', 'Error communicating with globus nexus service (status=502) (utctime=2022-01-22T18:24:10.474846)', 'gEExD5c1X')

  ||
  VV

status: 500
code: InternalError
message: Error communicating with globus nexus service (status=502) (utctime=2022-01-22T18:24:10.474846)
request_id: gEExD5c1X
```

The `request_id` is the single most useful field for diagnosis. After that, the next most important piece of information is the time at which the error occurred. In this case, that's available from the `message` field, but if you see a similar error without the time, please include the time/date information in error reports to the best of your ability.

With the SDKv3 behavior, most minor issues should be invisible to you as a user. Consistently seeing these types of errors may indicate a deeper problem. I'm going to close this and raise this with the team so that they are aware -- there's nothing for the SDK to do in this case. However, if this is a recurring issue, and it sounds like it may be, please take the time to file a support ticket (support@globus.org), and you can refer back to this issue.
