### ISSUE TITLE
Confusing __str__() implementation for OAuthTokenResponse

### ISSUE THREAD

**Issue by rgov** [globus/globus-sdk-python#639]
https://github.com/globus/globus-sdk-python/blob/836bf5954b13451adf168a3f67dad0f65d280976/src/globus_sdk/services/auth/response/oauth.py#L227-L230

This makes it so that if you `print()` a `OAuthTokenResponse` instance, it shows you something different than if you actually tried to access members of the object.

E.g., it shows that there is a top-level `transfer.api.globus.org` key but in reality this is under `other_tokens`.

**Comment by sirosen** [comment]
I tend to agree that it could be confusing. The `__str__` here is meant to be informational and extract useful detail from the response, but it drops other fields and the classname.

I still prefer that `__str__` shows `by_resource_server` rather than the `other_tokens` array. `by_resource_server` reshapes the data to fit the application model better and converts `expires_in` to `expires_at_seconds` (which is subtle but important, as you may want to store response data and reference it later).

I'm going to run an updated variant of this past our team and see what people think.
