### ISSUE TITLE
Rename Service Clients to not conflict with OAuth2 usage of the word "Client"?

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#90]
As I've started working on some more thorough tutorial documents, the word "Client" is a sticking point.

Often, when talking about Auth concepts, we end up focused on things like the `client_id` and having to involve the language of OAuth2 Clients.
That seems inherently confusing when we've been calling the service adapters `TransferClient`, `AuthClient`, etc.

Is there an alternative, suitable name?
One option is to simply name them by the services that they represent, so it becomes

`TransferClient` -> `GlobusTransfer`

and

`AuthClient` -> `GlobusAuth`

But we would presumably keep the OAuth2-oriented subclasses of `GlobusAuth` named by the type of "OAuth2 Client" that they represent.

Is this just a recipe for more confusion?

**Comment by mattias-lidman** [comment]
> One option is to simply name them by the services that they represent

This seems reasonable.

**Comment by jaswilli** [comment]
That usage of "client" hasn't really been bothering me. Maybe it's because I always `transfer = TransferClient(...)` and I don't have a bunch of "client" vars littered around?

Not opposed to a rename if everyone else is on board, although if we do I'm not sure we should start prefacing everything with `Globus`. I'd probably go straight `Transfer`, `Auth`, etc., or maybe something like `TransferManager`.

**Comment by sirosen** [comment]
In a discussion about this, we've decided to punt on this for now.

We might revisit it in the future if users are actually confused.

**Comment by sirosen** [comment]
1.0 has shipped, so this has already set sail, IMO.

If we need to come back to this and rename to `TransferManager`, `AuthManager`, or `Transfer`, `Auth`, etc. we can do that in 2.0 or 10.0.
