### ISSUE TITLE
Cannot change `limit` in paginated.post_search()

### ISSUE THREAD

**Issue by nocollier** [globus/globus-sdk-python#905]
I am working on a paginated post_search and I am having hard time controlling the number of entries in each page. In the following code you will see that I set a limit of 200 in the query_data, and a limit of 300 in the post_search call. However, if you execute this script you will see only 100 items per page--neither limit value is used. Am I misunderstanding the documentation or is this a bug? As I understand the documentation, I expected to see 300 per page as setting the parameter in the post_search call should override the one in the query data.

Note that the limit keyword of post_search does work as expected if I am not using the paginated version.

```python
from globus_sdk import SearchClient

index_id = "d927e2d9-ccdb-48e4-b05d-adbc3d97bbc5"
query_data = {
    "q": "",
    "limit": 200,
    "filters": [
        {"type": "match_any", "field_name": "type", "values": ["Dataset"]},
        {"type": "match_any", "field_name": "experiment_id", "values": ["historical"]},
        {"type": "match_any", "field_name": "variant_label", "values": ["r1i1p1f1"]},
        {"type": "match_any", "field_name": "table_id", "values": ["Lmon"]},
    ],
    "facets": [],
    "sort": [],
}
sc = SearchClient()
for response in sc.paginated.post_search(index_id, query_data, limit=300):
    print(
        f"{response['offset']} of {response['total']} next={response['has_next_page']}"
    )
```

```
0 of 1332 next=True
100 of 1332 next=True
200 of 1332 next=True
300 of 1332 next=True
400 of 1332 next=True
500 of 1332 next=True
600 of 1332 next=True
700 of 1332 next=True
800 of 1332 next=True
900 of 1332 next=True
1000 of 1332 next=True
1100 of 1332 next=True
1200 of 1332 next=True
1300 of 1332 next=False
```

**Comment by nocollier** [comment]
I have looked into this further and it seems to me that the `limit` keyword is not used in the paginated version of the method. If you look at this [line](https://github.com/globus/globus-sdk-python/blob/14dbe289e1e49aaab0e612f8e54020486bdc1283/src/globus_sdk/services/search/client.py#L275) you see that the `post_search` method has the `paginated` decorator where the `page_size=100`. This is used when the client is instantiated to build paginated versions of any routine with this decorator. However your page size is fixed. If I add:

```python
sc.paginated.post_search._paginator_params['page_size'] = 300
```

just above my `post_search` then I get the expected pagination. But this is more of a hack, is there a more canonical method of selecting page size in paginated calls?

**Comment by sirosen** [comment]
Sorry about the delayed response here. I missed your initial issue coming in and am just reading this now.

I think one less hacky feeling approach would be to make the paginated call to get the paginator and then modify the `limit` parameter which it is using.
That is
```python
paginator = sc.paginated.post_search(index_id, query_data)
paginator.page_size = 300
for response in paginator:
    ...
```

I'm currently looking at the limit+offset pagination code to see if there are issues with this suggestion, and I believe it will work safely.
For now, that is what I would recommend for this customization.

---

More broadly, what you're asking about is how to control pagination parameters (rather than the parameters to the paginated call).

I need to think harder about what a good interface looks like. It might be that we need to recognize parameters which are valid for both purposes (like `limit`) and "lift" them into the paginator if appropriate, such that a paginated search with `limit=300` "just works". But this model needs to work consistently for other pagination modes in order for us to confidently offer that as our interface.

For now, I think building a paginator and then adjusting its attributes is the best way. There are other possibilities for the future, but we'll need to do some analysis to figure out what's best for all cases.
